<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            // consoles
            [
                'productName' => 'PS5 Disc 800GB',
                'description' => 'Sony PlayStation 5 console with Ultra HD Blu-ray drive and 825GB internal storage. Delivers fast loading, smooth frame rates and stunning 4K HDR performance for next-gen gaming experiences.',
                'price' => 449.99,
                'stockQuantity' => 10,
                'image' => 'ps5.png',
                'category' => 'consoles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'PS5 Digital 800GB',
                'description' => 'PlayStation 5 Digital Edition featuring 825GB SSD storage and lightning fast load times. Ideal for players who prefer digital game libraries and immersive next-gen performance.',
                'price' => 389.99,
                'stockQuantity' => 10,
                'image' => 'ps5 digital.png',
                'category' => 'consoles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Xbox Series X 1TB',
                'description' => 'Microsoft Xbox Series X with 1TB SSD, offering true 4K gaming, quick resume and ultra-fast processing. Designed for premium performance across blockbuster titles and Game Pass exclusives.',
                'price' => 429.99,
                'stockQuantity' => 10,
                'image' => 'xbox.png',
                'category' => 'consoles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Xbox Series S 1TB',
                'description' => 'Compact Xbox Series S with 1TB SSD storage, perfect for digital downloads and Game Pass access. Sleek, quiet and built for smooth next-gen gameplay at great value.',
                'price' => 299.99,
                'stockQuantity' => 10,
                'image' => 'xbox series s.png',
                'category' => 'consoles',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Nintendo Switch Console',
                'description' => 'Nintendo Switch hybrid system allowing handheld and docked TV play. Enjoy family games, exclusives and portable entertainment anytime, anywhere.',
                'price' => 249.99,
                'stockQuantity' => 10,
                'image' => 'nintendo switch.png',
                'category' => 'consoles',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Games
            [
                'productName' => 'Lego World Nintendo',
                'description' => 'Creative open-world adventure built entirely from LEGO bricks. Explore, build and unlock unique characters and vehicles. Perfect for all ages and family gaming sessions.',
                'price' => 29.99,
                'stockQuantity' => 10,
                'image' => 'lego world nintendo .png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Mario Kart World Nintendo',
                'description' => 'Fast-paced kart racing with iconic Nintendo characters and exciting tracks. Compete with friends locally or online for endless replay value.',
                'price' => 39.99,
                'stockQuantity' => 10,
                'image' => 'mario kart world nintendo.png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Warzone PS5',
                'description' => 'Action-packed battle royale with next-gen graphics and smoother frame rates on PS5. Squad up, drop in and fight for survival across massive dynamic maps.',
                'price' => 34.99,
                'stockQuantity' => 10,
                'image' => 'Warzone ps5.png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'FIFA 26 PS5',
                'description' => 'Next-generation football gameplay with updated teams, new animation systems and enhanced matchday immersion on PS5. Ultimate Team and Career modes included.',
                'price' => 59.99,
                'stockQuantity' => 10,
                'image' => 'fifa 26 ps5.png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'FIFA 26 Xbox',
                'description' => 'Football simulation with improved AI, realistic physics and full licensed leagues. Optimized for Xbox performance across online and offline modes.',
                'price' => 59.99,
                'stockQuantity' => 10,
                'image' => 'fifa 26 xbox.png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Sniper Elite 4 Nintendo',
                'description' => 'Stealth sniper experience set in World War II environments. Plan long-range shots, use tactical gadgets and infiltrate enemy strongholds on the go.',
                'price' => 24.99,
                'stockQuantity' => 10,
                'image' => 'sniper elite 4 nintendo.png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Warzone Xbox',
                'description' => 'Free-roam battle royale action with cross-platform multiplayer support on Xbox. Drop in solo or with your squad, complete contracts and survive to win.',
                'price' => 34.99,
                'stockQuantity' => 10,
                'image' => 'warzone xbox.png',
                'category' => 'games',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Accesories
            [
                'productName' => 'Xbox Controller',
                'description' => 'Official wireless controller designed for Xbox consoles with textured grips and responsive triggers. Ideal for competitive gaming and smooth online play.',
                'price' => 49.99,
                'stockQuantity' => 10,
                'image' => 'xbox controller.png',
                'category' => 'accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Scuff Controller (PS5)',
                'description' => 'Custom-designed PS5 Scuf style controller with adjustable paddles and improved grip. Built for precision and enhanced control during fast-paced gameplay.',
                'price' => 139.99,
                'stockQuantity' => 10,
                'image' => 'scuff controler.png',
                'category' => 'accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'PS5 Controller',
                'description' => 'DualSense wireless controller for PlayStation 5 featuring adaptive triggers and haptic feedback. Comfortable, durable and perfect for long gaming sessions.',
                'price' => 59.99,
                'stockQuantity' => 10,
                'image' => 'ps5 controller.png',
                'category' => 'accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Nintendo Controller',
                'description' => 'Nintendo wireless controller suitable for multiple Switch titles. Lightweight, ergonomic and ideal for local multiplayer and portable gaming.',
                'price' => 29.99,
                'stockQuantity' => 10,
                'image' => 'nintendo controller.png',
                'category' => 'accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Gaming Headset (Binnune)',
                'description' => 'High-performance Binnune gaming headset with noise-cancelling mic and comfortable over-ear padding. Compatible with PlayStation, Xbox, PC and Nintendo Switch.',
                'price' => 34.99,
                'stockQuantity' => 10,
                'image' => 'gaming headset for both.png',
                'category' => 'accessories',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Software services
            [
                'productName' => 'Xbox Gift Card',
                'description' => 'Digital Xbox gift card for purchasing games, add-ons and subscriptions on the Microsoft Store. Ideal for gifting or topping up your account balance.',
                'price' => 25.00,
                'stockQuantity' => 10,
                'image' => 'xbox gift card.png',
                'category' => 'software services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'PlayStation Plus',
                'description' => 'Subscription service for PS4 and PS5 including online multiplayer, cloud saves and monthly game downloads. Access exclusive members-only features and discounts.',
                'price' => 49.99,
                'stockQuantity' => 10,
                'image' => 'playstation plus.png',
                'category' => 'software services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Nintendo eShop Card',
                'description' => 'Nintendo eShop top-up card for purchasing digital games and content on the Switch. Quick, secure and perfect for players who buy titles digitally.',
                'price' => 20.00,
                'stockQuantity' => 10,
                'image' => 'nintendo game pass.png',
                'category' => 'software services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Xbox Game Pass',
                'description' => 'Monthly subscription service granting access to hundreds of Xbox titles, day-one releases and cloud gaming. Best value option for regular Xbox players.',
                'price' => 10.99,
                'stockQuantity' => 10,
                'image' => 'xbox game pass.png',
                'category' => 'software services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'EA Play',
                'description' => 'Monthly subscription offering access to a growing library of EA games, trial versions and exclusive in-game rewards. Perfect for FIFA, Battlefield and Need for Speed fans.',
                'price' => 5.99,
                'stockQuantity' => 10,
                'image' => 'ea play.png',
                'category' => 'software services',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Steam Card',
                'description' => 'Digital Steam wallet top-up usable on thousands of PC games and downloadable content. Fast and secure way to purchase titles, DLC and in-game items.',
                'price' => 20.00,
                'stockQuantity' => 10,
                'image' => 'steam card.png',
                'category' => 'software services',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Gaming Monitor
            [
                'productName' => 'LG Monitor 27” 2560 x 1440',
                'description' => '27-inch LG gaming monitor with QHD resolution for crisp visuals and smooth gameplay. Ideal for FPS, RPG, and competitive online matches.',
                'price' => 229.99,
                'stockQuantity' => 10,
                'image' => 'Lg monitor.png',
                'category' => 'Gaming Monitors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Acer Monitor 27”',
                'description' => '27-inch Acer gaming monitor with fast response times and vivid colours. Perfect for immersive gaming setups and daily use.',
                'price' => 189.99,
                'stockQuantity' => 10,
                'image' => 'acer monitor.png',
                'category' => 'Gaming Monitors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'NOC Monitor 27”',
                'description' => '27-inch NOC LED gaming monitor built for everyday gaming performance. Reliable display quality for consoles and PC gaming.',
                'price' => 159.99,
                'stockQuantity' => 10,
                'image' => 'noc monitor.png',
                'category' => 'Gaming Monitors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'Samsung Monitor 27”',
                'description' => '27-inch Samsung display with sharp visuals and smooth refresh rate. Great for competitive gaming and streaming.',
                'price' => 249.99,
                'stockQuantity' => 10,
                'image' => 'sam monitor.png',
                'category' => 'Gaming Monitors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'productName' => 'HP Monitor 27”',
                'description' => '27-inch HP monitor designed for clear visuals and low input lag. Suitable for home gaming, work, and media consumption.',
                'price' => 179.99,
                'stockQuantity' => 10,
                'image' => 'hp monitor.png',
                'category' => 'Gaming Monitors',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}